INSERT INTO pessoas2 (FirstName, LastName, Idade, Cidade, Estado, Pais) VALUES
('Carlos', 'Silva', 30, 'São Paulo', 'São Paulo', 'Brasil'),
('Maria', 'Oliveira', 32, 'Rio de Janeiro', 'Rio de Janeiro', 'Brasil'),
('Carlos', 'Santos', 40, 'Belo Horizonte', 'Minas Gerais', 'Brasil'),
('Ana', 'Lima', 35, 'Curitiba', 'Paraná', 'Brasil'),
('Cris', 'Flores', 25, 'Sao Luis', 'Maranhao', 'Brasil'),
('Fabiola', 'Cristine', 28, 'Sao Luis', 'Maranhao', 'Brasil'),
('Pedro', 'Silva', 22, 'Sao Luis', 'Maranhao', 'Brasil'),
('Cristinee', 'Mousinho', 22, 'Sao Paulo', 'Sao Paulo', 'Brasil'),
('Pedro', 'Martins', 28, 'Salvador', 'Bahia', 'Brasil'),
('Mateus', 'Ferreira', 32, 'Fortaleza', 'Ceará', 'Brasil'),
('Fernanda', 'Almeida', 27, 'Recife', 'Pernambuco', 'Brasil'),
('Ricardo', 'Pereira', 45, 'Porto Alegre', 'Rio Grande do Sul', 'Brasil'),
('Juliana', 'Rodrigues', 29, 'Brasília', 'Distrito Federal', 'Brasil'),
('André', 'Costa', 34, 'Manaus', 'Amazonas', 'Brasil'),
('Sophie', 'Dubois', 26, 'Paris', 'Île-de-France', 'França'),
('Pierre', 'Lemoine', 38, 'Lyon', 'Auvergne-Rhône-Alpes', 'França'),
('Camille', 'Moreau', 31, 'Marselha', 'Provence-Alpes-Côte d’Azur', 'França'),
('Antoine', 'Bernard', 29, 'Toulouse', 'Occitanie', 'França'),
('Élise', 'Lefevre', 33, 'Nice', 'Provence-Alpes-Côte d’Azur', 'França'),
('James', 'Smith', 45, 'New York', 'New York', 'Estados Unidos'),
('Emily', 'Johnson', 28, 'Los Angeles', 'California', 'Estados Unidos'),
('Michael', 'Brown', 35, 'Chicago', 'Illinois', 'Estados Unidos'),
('Sarah', 'Davis', 30, 'Houston', 'Texas', 'Estados Unidos'),
('David', 'Miller', 40, 'Miami', 'Florida', 'Estados Unidos'),
('Liam', 'Wilson', 29, 'Toronto', 'Ontario', 'Canadá'),
('Olivia', 'Anderson', 27, 'Vancouver', 'British Columbia', 'Canadá'),
('Noah', 'White', 34, 'Montreal', 'Quebec', 'Canadá'),
('Emma', 'Harris', 31, 'Calgary', 'Alberta', 'Canadá'),
('Benjamin', 'Clark', 36, 'Ottawa', 'Ontario', 'Canadá'),
('Mateo', 'Gonzalez', 33, 'Madri', 'Madri', 'Espanha'),
('Lucia', 'Fernandez', 26, 'Barcelona', 'Catalunha', 'Espanha'),
('Diego', 'Lopez', 37, 'Valência', 'Comunidade Valenciana', 'Espanha'),
('Sofia', 'Martinez', 28, 'Sevilha', 'Andaluzia', 'Espanha'),
('Alejandro', 'Perez', 41, 'Bilbao', 'País Basco', 'Espanha'),
('Giovanni', 'Rossi', 30, 'Roma', 'Lazio', 'Itália'),
('Francesca', 'Bianchi', 32, 'Milão', 'Lombardia', 'Itália'),
('Luca', 'Ferrari', 38, 'Nápoles', 'Campânia', 'Itália'),
('Martina', 'Ricci', 29, 'Turim', 'Piemonte', 'Itália'),
('Alessandro', 'Conti', 32, 'Florença', 'Toscana', 'Itália'),
('Hans', 'Müller', 45, 'Berlim', 'Berlim', 'Alemanha'),
('Sophia', 'Schmidt', 28, 'Munique', 'Baviera', 'Alemanha'),
('Felix', 'Wagner', 35, 'Hamburgo', 'Hamburgo', 'Alemanha'),
('Anna', 'Hoffmann', 31, 'Frankfurt', 'Hessen', 'Alemanha'),
('Leon', 'Schneider', 40, 'Colônia', 'Renânia do Norte-Vestfália', 'Alemanha'),
('Jorge', 'Ramirez', 33, 'Cidade do México', 'CDMX', 'México'),
('Camila', 'Gomez', 26, 'Guadalajara', 'Jalisco', 'México'),
('Luis', 'Hernandez', 37, 'Monterrey', 'Nuevo León', 'México'),
('Valentina', 'Torres', 28, 'Cancún', 'Quintana Roo', 'México'),
('Andrés', 'Diaz', 41, 'Puebla', 'Puebla', 'México');
