-- INSERINDO ALUNOS NA TABELA ALUNO
INSERT INTO aluno (nomecompleto, curso) VALUES
('ANA BEATRIZ TORRES DIAS LEITE', 'Sistema da Informação'),
('ANTONIA ALICE DA SILVA TORRES MUNIZ', 'Engenharia Civil'),
('AUGUSTO JOHNYE RIBEIRO CAVALCANTE DIAS', 'Ciência da Computação'),
('BRUNO OCTAVIO OLIVEIRA PACHECO FERREIRA', 'Engenharia Civil'),
('CARLOS CAUA GOMES PINTO NETO', 'Engenharia da Computação'),
('CHRISTIAN TAYLAN MACHADO SILVA ALVES', 'Ciência da Computação'),
('DANIEL CARDOSO NUNES LOPES', 'Sistema da Informação'),
('DANILO BARBOSA MUNIZ SOUSA', 'Engenharia Elétrica'),
('DAVI CARDOSO NUNES GOMES', 'Engenharia Elétrica'),
('DAVI DA COSTA PEREIRA', 'Ciência da Computação'),
('DIEGO DOS SANTOS TEIXEIRA CHAGAS MUNIZ', 'Engenharia Civil'),
('DJAILSON SILVA DE LIMA NETO', 'Engenharia Civil'),
('FERNANDA PEREIRA COSTA DIAS', 'Engenharia Civil'),
('FHAEL ERICKI GOMES NUNES SILVA', 'Sistema da Informação'),
('GUILHERME DALESSANDRO FRANCO PIRES SOUSA', 'Engenharia Civil'),
('HENRIQUE GABRIEL PRAZERES DE SA BARROS', 'Sistema da Informação'),
('HENZO GABRIEL LIMA DA LUZ COSTA', 'Engenharia Civil'),
('HUDSON FELIPE COSTA DE JESUS DIAS', 'Engenharia da Computação'),
('HUGO GABRYEL LOURENCO SOUSA PAVÃO', 'Engenharia Civil'),
('JENNIFER SAMYRA PEREIRA GONCALVES FERREIRA', 'Ciência da Computação'),
('JHEIMISSON GABRIEL NASCIMENTO BARROS SOUZA', 'Engenharia Elétrica'),
('JHONATA SILVA SILVA', 'Ciência da Computação'),
('JOAO FELIPE OLIVEIRA COSTA SOEIRO', 'Engenharia Civil'),
('JOSE ARTHUR SILVA VIANA DIAS', 'Engenharia da Computação'),
('JOSE HERIC MONTEIRO MONTEIRO BATALHA SILVA', 'Engenharia Elétrica'),
('JOSE WILLIAN DOS REIS OLIVEIRA COSTA', 'Sistema da Informação'),
('JOSUE COELHO FREIRE JUNIOR PAVÃO', 'Engenharia da Computação'),
('JUAN FABRICIO DOS SANTOS SOEIRO DIAS', 'Engenharia Elétrica'),
('LUCAS ONEBIO DE AMORIM LOPES BARROS', 'Engenharia Elétrica'),
('LUCAS PONTES DE SOUZA DIAS', 'Ciência da Computação'),
('LUCAS SANTOS DA SILVA PRADO VIANA', 'Sistema da Informação'),
('LUIS DAVI MARTINS ALVES NETO', 'Engenharia Elétrica'),
('MARCELA DO NASCIMENTO PINHEIRO SANTOS', 'Ciência da Computação'),
('MYCKAEL CARVALHO MELO SOUZA', 'Sistema da Informação'),
('PEDRO HORI MACHADO FERREIRA SOUSA', 'Engenharia da Computação'),
('PEDRO VICTOR PEREIRA SILVA SOUZA', 'Sistema da Informação'),
('RAIMUNDO MATEUS MARQUES DA COSTA DIAS PEREIRA', 'Engenharia Elétrica'),
('ROMULO SANTOS PIRES NETO', 'Ciência da Computação'),
('SAVIO FELIPE SOUSA FREITAS LOPES', 'Engenharia Elétrica'),
('VALENTIM EXPEDITO PINHEIRO DE CARVALHO FILHO COSTA', 'Engenharia Civil'),
('WELINTON FELLIPE ARAUJO AIRES DE ABREU SOUSA', 'Engenharia Elétrica'),
('WENDEL DIAS DE BRITO JUNIOR SOEIRO', 'Ciência da Computação'),
('ZAYON REIS PIMENTEL SILVA SOUZA', 'Engenharia Civil');
