INSERT INTO Informacoes (Id, NomeCompleto, Curso, Disciplina, Idade) VALUES
(1, 'ANA BEATRIZ TORRES DIAS LEITE', 'Sistema da Informação', 'Programação Orientada a Objeto I', 11),
(2, 'ANTONIA ALICE DA SILVA TORRES MUNIZ', 'Engenharia Civil', 'Banco de Dados', 11),
(3, 'AUGUSTO JOHNYE RIBEIRO CAVALCANTE DIAS', 'Ciência da Computação', 'Banco de Dados', 7),
(4, 'BRUNO OCTAVIO OLIVEIRA PACHECO FERREIRA', 'Engenharia Civil', 'Programação Orientada a Objeto I', 10),
(5, 'CARLOS CAUA GOMES PINTO NETO', 'Engenharia da Computação', 'Programação Orientada a Objeto II', 11),
(6, 'DANIELLY COSTA RIBEIRO', 'Engenharia da Computação', 'Banco de Dados', 11),
(7, 'DAVID LUCAS DOS SANTOS LOPES', 'Engenharia Civil', 'Banco de Dados', 11),
(8, 'ELOY MOURA MACIEL FILHO', 'Engenharia da Computação', 'Programação Orientada a Objeto II', 11),
(9, 'EMANUEL BRUNO DA CONCEICAO OLIVEIRA', 'Ciência da Computação', 'Programação Orientada a Objeto II', 11),
(10, 'EMANUELLE VITÓRIA CUNHA LIMA', 'Sistema da Informação', 'Banco de Dados', 9),
(11, 'FABIO CAYO DE MORAIS VELOSO', 'Sistema da Informação', 'Programação Orientada a Objeto II', 9),
(12, 'FELIPE DE JESUS NASCIMENTO', 'Engenharia Civil', 'Banco de Dados', 10),
(13, 'FRANCISCO DAS CHAGAS ARAUJO MENDES', 'Ciência da Computação', 'Programação Orientada a Objeto I', 11),
(14, 'FRANCISCO DE ASSIS REIS LIMA NETO', 'Sistema da Informação', 'Banco de Dados', 11),
(15, 'FRANCISCO LEONARDO RODRIGUES DA SILVA', 'Ciência da Computação', 'Programação Orientada a Objeto I', 11),
(16, 'GABRIEL GUIMARAES MORAIS', 'Engenharia da Computação', 'Programação Orientada a Objeto I', 10),
(17, 'GABRIELA VIEIRA DOS SANTOS MORAIS', 'Sistema da Informação', 'Banco de Dados', 10),
(18, 'GUSTAVO HENRIQUE RIBEIRO SILVA', 'Sistema da Informação', 'Programação Orientada a Objeto I', 11),
(19, 'IGOR MATEUS BARROS SILVA', 'Ciência da Computação', 'Programação Orientada a Objeto II', 10),
(20, 'ISAQUE COSTA MACHADO', 'Ciência da Computação', 'Programação Orientada a Objeto II', 11),
(21, 'ISABELLE MARIA DOS SANTOS PINHEIRO', 'Engenharia Civil', 'Banco de Dados', 10),
(22, 'ISABELLY RIBEIRO DOS SANTOS', 'Engenharia Civil', 'Banco de Dados', 11),
(23, 'ISADORA HELENA SERRA SOARES', 'Sistema da Informação', 'Banco de Dados', 9),
(24, 'JAILSON DOS SANTOS NUNES', 'Engenharia Civil', 'Banco de Dados', 10),
(25, 'JONATHAN DOS SANTOS NASCIMENTO', 'Engenharia da Computação', 'Banco de Dados', 11),
(26, 'JOSE RYAN DO NASCIMENTO MORAIS', 'Ciência da Computação', 'Banco de Dados', 11),
(27, 'JULIA EDUARDA COSTA RIBEIRO', 'Engenharia Civil', 'Banco de Dados', 11),
(28, 'KAROLINE PATRICIA SILVA COSTA', 'Sistema da Informação', 'Banco de Dados', 11),
(29, 'KETRYN LARISSA DA SILVA RODRIGUES', 'Engenharia Civil', 'Banco de Dados', 11),
(30, 'LETICIA MARIA LIMA MARQUES', 'Sistema da Informação', 'Banco de Dados', 10),
(31, 'LUCAS ANDRE DOS SANTOS ARAUJO', 'Engenharia Civil', 'Banco de Dados', 11),
(32, 'LUCAS RICARDO DA COSTA REIS', 'Engenharia da Computação', 'Banco de Dados', 11),
(33, 'LUIS FERNANDO NASCIMENTO FERREIRA', 'Engenharia Civil', 'Banco de Dados', 11),
(34, 'LUIZA VICTORIA MOREIRA SOUSA', 'Sistema da Informação', 'Banco de Dados', 11),
(35, 'MARCOS VINICIUS SOUSA PEREIRA', 'Sistema da Informação', 'Banco de Dados', 11),
(36, 'MIRELLY DE JESUS SANTOS NASCIMENTO', 'Sistema da Informação', 'Banco de Dados', 11),
(37, 'RAFAEL LUCAS DA COSTA ARAUJO', 'Sistema da Informação', 'Banco de Dados', 11),
(38, 'RAIMUNDO NONATO DOS SANTOS FILHO', 'Engenharia Civil', 'Banco de Dados', 11),
(39, 'RAISSA MAYARA SILVA DOS SANTOS', 'Sistema da Informação', 'Banco de Dados', 11),
(40, 'RAYSSA NAYANE MONTEIRO SILVA', 'Engenharia Civil', 'Banco de Dados', 11),
(41, 'RAYSSA SUELY NASCIMENTO SOUSA', 'Sistema da Informação', 'Banco de Dados', 11),
(42, 'TALITA DE OLIVEIRA MORAIS', 'Sistema da Informação', 'Banco de Dados', 11),
(43, 'VANESSA PEREIRA DOS SANTOS', 'Sistema da Informação', 'Banco de Dados', 11);
